name = "discipline-api"
main = "server/worker.js"
compatibility_date = "2026-07-01"

[vars]
ADMOB_REWARDED_AD_UNIT_ID = "2001670311"

[[d1_databases]]
binding = "DB"
database_name = "discipline-db"
database_id = "PASTE_ID_FROM_wrangler_d1_create"
