name = "discipline-api"
main = "server/worker.js"
compatibility_date = "2026-07-01"

[triggers]
crons = ["17 * * * *"]

[vars]
ADMOB_REWARDED_AD_UNIT_ID = "2001670311"

[[d1_databases]]
binding = "DB"
database_name = "discipline-db"
database_id = "58d64196-499f-42ba-bd7e-a688b8bf64a4"
migrations_dir = "server/migrations"
